vis:
  service:
    sinoiv:
      url: "http://sinoiv.jd.com"
    gvr:
      url: "http://sinoiv.jd.com"
dc:
  host: 10.28.192.60
grpc:
  server:
    port: 9090
    address: 0.0.0.0
  client:
    GLOBAL:
      negotiationType: plaintext
    local-grpc-server:
      address: 'static://127.0.0.1:9090'
wgtRrpc:
  wgtId: "1"